sudo: false
language: node_js
node_js:
  - "node"
  - "6"
  - "6.0"
  - "5"
  - "5.0"
  - "4"
  - "4.0"
addons:
  firefox: "latest-esr"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - imagemagick
    - graphicsmagick
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - gcc-4.8
    - g++-4.8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - "export CXX=\"g++-4.8\" CC=\"gcc-4.8\""
after_success:
  - npm run coveralls
